site_name: Ejercicios Progra
copyright: Copyright &copy; 2020 - Progra UTFSM
theme:
  name: material
  language: es
  favicon: images/favicon.png
  icon: 
    logo: fontawesome/solid/laptop-code
    repo: fontawesome/brands/github
  features:
    - tabs
    - instant
    - navigation.expand
nav:
  - Inicio: index.md
  - Secuenciales: 
    - Inicio: secuenciales/index.md
    - Pitágoras: secuenciales/pitagoras.md
    - Área Triángulo: secuenciales/area-triangulo.md
    - Cilindro: secuenciales/cilindro.md
    - IMC: secuenciales/imc.md
    - Viaje: secuenciales/viaje.md
    - Notas: secuenciales/notas.md
    - Número Invertido: secuenciales/invertido.md
    - Convertidor segundos: secuenciales/segundos.md
    - Edad: secuenciales/edad.md
  - Condicionales:
    - Inicio: condicionales/index.md
    - Tablas de verdad: condicionales/tablas.md
    - Expresiones booleanas: condicionales/expresiones.md
    - Ejemplos: condicionales/ejemplos.md
    - Ecuación: condicionales/ecuacion.md
    - Calculadora: condicionales/calculadora.md
    - Círculo: condicionales/circulo.md
    - Mayor: condicionales/mayor.md
    - Tenis: condicionales/tenis.md
    - Triángulo: condicionales/triangulo.md
    - Horas extra: condicionales/horas_extra.md
    - Llamadas: condicionales/llamadas.md
  - Ciclos:
    - Ejemplos: ciclos/ejemplos.md
    - Ruteos: ciclos/ruteos.md 
    - Polígonos: ciclos/poligono.md
    - Serie: ciclos/serie.md
    - FizzBuzz: ciclos/fizzbuzz.md
    - Robot: ciclos/robot.md
    - Pirata: ciclos/pirata.md
    - Rango: ciclos/rango.md
    - VAN: ciclos/van.md
  - Funciones:
    - Comentarios: funciones/comentarios.md
    - Fuerza gravitacional: funciones/gravitacional.md
    - Invertir Número: funciones/invertir.md
    - Aproximación exponencial: funciones/exponencial.md
    - Método de Newton: funciones/newton.md
    - Crédito Hipotecario: funciones/hipoteca.md
    - Salario: funciones/salario.md
  - Strings:
    - Ejemplos: strings/ejemplos.md
    - Stringones: strings/stringones.md
    - Coincidencia: strings/coincidencia.md
    - ADN: strings/adn.md
    - Fechas mágicas: strings/fechas.md
    - Comparación: strings/comparacion.md
    - Contraseña: strings/contraseña.md
    - Veces: strings/veces.md
    - Palabra más larga: strings/larga.md
    - Eliminar: strings/eliminar.md
    - Asignaturas: strings/asignaturas.md
    - Patentes: strings/patentes.md
  - Listas:
    - Ejemplos: listas/ejemplos.md
    - Desviación estándar: listas/desviacion.md
    - Búsqueda secuencial: listas/busqueda_lineal.md
    - Búsqueda binaria: listas/busqueda_binaria.md
    - Merge: listas/merge.md
    - Cine: listas/cine.md
  - Tuplas:
    - Rectas: tuplas/rectas.md
    - Supermercado: tuplas/supermercado.md
  - Diccionarios:
    - Final Copa América: diccionarios/copa.md
    - Fórmula 1: diccionarios/formula1.md
    - Frutas y verduras: diccionarios/frutas-verduras.md
    - Números: diccionarios/numeros.md
    - Planetas: diccionarios/planetas.md
    - Sinónimos: diccionarios/sinonimos.md
  - Archivos:
    - Donantes: archivos/donantes.md
    - Consulta médica: archivos/consulta-medica.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js